Repository vaadin/cdi, pull requests merged in 2022-09, with the labels that each got.

#399 chore: Update README with the latest versions
  README.md
Labels: target/13.0, target/14.0, target/14.1, target/11.3, target/10.0

#408 chore: Update README with the latest versions (#399) (CP: 11.3)
  README.md
  pom.xml
Labels: cherry-pick

#398 fix: set load-on-startup for automatically registered Vaadin servlet
  vaadin-cdi/src/main/java/com/vaadin/cdi/CdiServletDeployer.java
Labels: target/14.0, target/14.1
